Vagrant.configure(2) do |config|
  config.vm.box   = "kurmaos"

  # SSH configuration
  config.ssh.username      = "root"
  config.ssh.forward_agent = true

  # Port forwarding... order is VM port first, then the Host port
  #config.vm.network :forwarded_port, guest:  80, host: 7070

  ## PROVIDER
  #
  # vmware_fusion
  config.vm.provider :vmware_fusion do |v|
    v.gui = false
    v.vmx["displayName"] = "kurmaos"
    v.vmx["numvcpus"]    = "4"
    v.vmx["memsize"]     = "2048"
  end
  config.vm.provider :vmware_desktop do |v|
    v.gui = false
    v.vmx["displayName"] = "kurmaos"
    v.vmx["numvcpus"]    = "4"
    v.vmx["memsize"]     = "2048"
  end
end
